/// Flutter icons MyIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyIcons
///      fonts:
///       - asset: fonts/MyIcons.ttf
///
/// 
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
/// * Web Symbols, Copyright (c) 2011 by Just Be Nice studio. All rights reserved.
///         Author:    Just Be Nice studio
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.justbenicestudio.com/
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
///
import 'package:flutter/widgets.dart';

class MyIcons {
  MyIcons._();

  static const _kFontFam = 'MyIcons';

  static const IconData icon_announcement = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData icon_archive = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData icon_arrow_down = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData icon_arrow_left = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData icon_arrow_right = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData icon_arrow_up = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData icon_at_symbol = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData icon_call = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData icon_calander = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData icon_building_1 = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData icon_code = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData icon_clock = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData icon_cheveron_down = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData icon_check_circle = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData icon_clipboard = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData icon_chat = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData icon_building = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData icon_browser_1 = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData icon_cart = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData icon_clip = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData icon_cheveron_up = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData icon_browser = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData icon_briefcase = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData icon_camera = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData icon_bookmark = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData icon_book = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData icon_call_incoming = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData icon_call_outgoing = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData icon_cheveron_left = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData icon_cheveron_right = const IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData icon_cog = const IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData icon_comment = const IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData icon_compass = const IconData(0xe820, fontFamily: _kFontFam);
  static const IconData icon_currency_dollar = const IconData(0xe821, fontFamily: _kFontFam);
  static const IconData icon_discount = const IconData(0xe822, fontFamily: _kFontFam);
  static const IconData icon_desktop = const IconData(0xe823, fontFamily: _kFontFam);
  static const IconData icon_external_link = const IconData(0xe824, fontFamily: _kFontFam);
  static const IconData icon_exclamation = const IconData(0xe825, fontFamily: _kFontFam);
  static const IconData icon_emotion_sad = const IconData(0xe826, fontFamily: _kFontFam);
  static const IconData icon_emotion_happy = const IconData(0xe827, fontFamily: _kFontFam);
  static const IconData icon_edit = const IconData(0xe828, fontFamily: _kFontFam);
  static const IconData icon_duplicate = const IconData(0xe829, fontFamily: _kFontFam);
  static const IconData icon_download = const IconData(0xe82a, fontFamily: _kFontFam);
  static const IconData icon_file = const IconData(0xe82b, fontFamily: _kFontFam);
  static const IconData icon_folder = const IconData(0xe82c, fontFamily: _kFontFam);
  static const IconData icon_hashtag = const IconData(0xe82d, fontFamily: _kFontFam);
  static const IconData icon_key = const IconData(0xe82e, fontFamily: _kFontFam);
  static const IconData icon_file_blank = const IconData(0xe82f, fontFamily: _kFontFam);
  static const IconData icon_file_minus = const IconData(0xe830, fontFamily: _kFontFam);
  static const IconData icon_file_plus = const IconData(0xe831, fontFamily: _kFontFam);
  static const IconData icon_film = const IconData(0xe832, fontFamily: _kFontFam);
  static const IconData icon_filter = const IconData(0xe833, fontFamily: _kFontFam);
  static const IconData icon_flag = const IconData(0xe834, fontFamily: _kFontFam);
  static const IconData icon_folder_minus = const IconData(0xe835, fontFamily: _kFontFam);
  static const IconData icon_group = const IconData(0xe836, fontFamily: _kFontFam);
  static const IconData icon_grid = const IconData(0xe837, fontFamily: _kFontFam);
  static const IconData icon_graph_bar = const IconData(0xe838, fontFamily: _kFontFam);
  static const IconData icon_globe = const IconData(0xe839, fontFamily: _kFontFam);
  static const IconData icon_folder_plus = const IconData(0xe83a, fontFamily: _kFontFam);
  static const IconData icon_information = const IconData(0xe83b, fontFamily: _kFontFam);
  static const IconData icon_inbox = const IconData(0xe83c, fontFamily: _kFontFam);
  static const IconData icon_image = const IconData(0xe83d, fontFamily: _kFontFam);
  static const IconData icon_home = const IconData(0xe83e, fontFamily: _kFontFam);
  static const IconData icon_help = const IconData(0xe83f, fontFamily: _kFontFam);
  static const IconData icon_heart = const IconData(0xe840, fontFamily: _kFontFam);
  static const IconData icon_link = const IconData(0xe841, fontFamily: _kFontFam);
  static const IconData icon_location = const IconData(0xe842, fontFamily: _kFontFam);
  static const IconData info = const IconData(0xe843, fontFamily: _kFontFam);
  static const IconData icon_lock_open = const IconData(0xe844, fontFamily: _kFontFam);
  static const IconData icon_mail = const IconData(0xe845, fontFamily: _kFontFam);
  static const IconData icon_map = const IconData(0xe846, fontFamily: _kFontFam);
  static const IconData icon_menu = const IconData(0xe847, fontFamily: _kFontFam);
  static const IconData icon_microphone = const IconData(0xe848, fontFamily: _kFontFam);
  static const IconData icon_minus = const IconData(0xe849, fontFamily: _kFontFam);
  static const IconData icon_minus_circle = const IconData(0xe84a, fontFamily: _kFontFam);
  static const IconData icon_minus_square = const IconData(0xe84b, fontFamily: _kFontFam);
  static const IconData icon_mobile = const IconData(0xe84c, fontFamily: _kFontFam);
  static const IconData icon_moon = const IconData(0xe84d, fontFamily: _kFontFam);
  static const IconData icon_more_horiz = const IconData(0xe84e, fontFamily: _kFontFam);
  static const IconData icon_music = const IconData(0xe84f, fontFamily: _kFontFam);
  static const IconData icon_notification = const IconData(0xe850, fontFamily: _kFontFam);
  static const IconData icon_plus = const IconData(0xe851, fontFamily: _kFontFam);
  static const IconData icon_plus_circle = const IconData(0xe852, fontFamily: _kFontFam);
  static const IconData icon_plus_square = const IconData(0xe853, fontFamily: _kFontFam);
  static const IconData icon_print = const IconData(0xe854, fontFamily: _kFontFam);
  static const IconData icon_puzzle = const IconData(0xe855, fontFamily: _kFontFam);
  static const IconData icon_refresh = const IconData(0xe856, fontFamily: _kFontFam);
  static const IconData icon_server = const IconData(0xe857, fontFamily: _kFontFam);
  static const IconData icon_search = const IconData(0xe858, fontFamily: _kFontFam);
  static const IconData icon_rocket = const IconData(0xe859, fontFamily: _kFontFam);
  static const IconData icon_repeat = const IconData(0xe85a, fontFamily: _kFontFam);
  static const IconData icon_speaker = const IconData(0xe85b, fontFamily: _kFontFam);
  static const IconData icon_thumb_up = const IconData(0xe85c, fontFamily: _kFontFam);
  static const IconData icon_thumb_down = const IconData(0xe85d, fontFamily: _kFontFam);
  static const IconData icon_tag = const IconData(0xe85e, fontFamily: _kFontFam);
  static const IconData icon_tablet = const IconData(0xe85f, fontFamily: _kFontFam);
  static const IconData icon_star = const IconData(0xe860, fontFamily: _kFontFam);
  static const IconData icon_store = const IconData(0xe861, fontFamily: _kFontFam);
  static const IconData icon_trash = const IconData(0xe862, fontFamily: _kFontFam);
  static const IconData icon_trending_down = const IconData(0xe863, fontFamily: _kFontFam);
  static const IconData icon_trending_up = const IconData(0xe864, fontFamily: _kFontFam);
  static const IconData icon_trophy = const IconData(0xe865, fontFamily: _kFontFam);
  static const IconData icon_upload = const IconData(0xe866, fontFamily: _kFontFam);
  static const IconData icon_user = const IconData(0xe867, fontFamily: _kFontFam);
  static const IconData icon_user_check = const IconData(0xe868, fontFamily: _kFontFam);
  static const IconData icon_user_minus = const IconData(0xe869, fontFamily: _kFontFam);
  static const IconData icon_user_plus = const IconData(0xe86a, fontFamily: _kFontFam);
  static const IconData icon_video = const IconData(0xe86b, fontFamily: _kFontFam);
  static const IconData icon_view = const IconData(0xe86c, fontFamily: _kFontFam);
  static const IconData icon_x = const IconData(0xe86d, fontFamily: _kFontFam);
  static const IconData icon_x_circle = const IconData(0xe86e, fontFamily: _kFontFam);
  static const IconData icon_x_square = const IconData(0xe86f, fontFamily: _kFontFam);
  static const IconData icon_zoom_in = const IconData(0xe870, fontFamily: _kFontFam);
  static const IconData icon_zoom_out = const IconData(0xe871, fontFamily: _kFontFam);
  static const IconData info_circled = const IconData(0xe872, fontFamily: _kFontFam);
  static const IconData cancel = const IconData(0xe873, fontFamily: _kFontFam);
  static const IconData user_outline = const IconData(0xe874, fontFamily: _kFontFam);
  static const IconData user = const IconData(0xe875, fontFamily: _kFontFam);
  static const IconData users_outline = const IconData(0xe876, fontFamily: _kFontFam);
  static const IconData users = const IconData(0xe877, fontFamily: _kFontFam);
  static const IconData user_add_outline = const IconData(0xe878, fontFamily: _kFontFam);
  static const IconData user_add = const IconData(0xe879, fontFamily: _kFontFam);
  static const IconData user_delete_outline = const IconData(0xe87a, fontFamily: _kFontFam);
  static const IconData user_delete = const IconData(0xe87b, fontFamily: _kFontFam);
  static const IconData cancel_outline = const IconData(0xe87c, fontFamily: _kFontFam);
  static const IconData cancel_1 = const IconData(0xe87d, fontFamily: _kFontFam);
  static const IconData cancel_circled_outline = const IconData(0xe87e, fontFamily: _kFontFam);
  static const IconData info_outline = const IconData(0xe87f, fontFamily: _kFontFam);
  static const IconData cog = const IconData(0xe880, fontFamily: _kFontFam);
  static const IconData left_open = const IconData(0xe881, fontFamily: _kFontFam);
  static const IconData right_open_outline = const IconData(0xe882, fontFamily: _kFontFam);
  static const IconData right_open = const IconData(0xe883, fontFamily: _kFontFam);
  static const IconData left_open_outline = const IconData(0xe884, fontFamily: _kFontFam);
  static const IconData left = const IconData(0xe885, fontFamily: _kFontFam);
  static const IconData up = const IconData(0xe886, fontFamily: _kFontFam);
  static const IconData right = const IconData(0xe887, fontFamily: _kFontFam);
  static const IconData down = const IconData(0xe888, fontFamily: _kFontFam);
  static const IconData play = const IconData(0xe889, fontFamily: _kFontFam);
  static const IconData stop = const IconData(0xe88a, fontFamily: _kFontFam);
  static const IconData pause_outline = const IconData(0xe88b, fontFamily: _kFontFam);
  static const IconData pause = const IconData(0xe88c, fontFamily: _kFontFam);
  static const IconData fast_fw_outline = const IconData(0xe88d, fontFamily: _kFontFam);
  static const IconData fast_fw = const IconData(0xe88e, fontFamily: _kFontFam);
  static const IconData rewind_outline = const IconData(0xe88f, fontFamily: _kFontFam);
  static const IconData record_outline = const IconData(0xe890, fontFamily: _kFontFam);
  static const IconData record = const IconData(0xe891, fontFamily: _kFontFam);
  static const IconData beaker = const IconData(0xe892, fontFamily: _kFontFam);
  static const IconData truck = const IconData(0xe893, fontFamily: _kFontFam);
  static const IconData star = const IconData(0xe894, fontFamily: _kFontFam);
  static const IconData progress_4 = const IconData(0xe895, fontFamily: _kFontFam);
  static const IconData cart = const IconData(0xe896, fontFamily: _kFontFam);
  static const IconData twitter = const IconData(0xf309, fontFamily: _kFontFam);
  static const IconData facebook = const IconData(0xf30c, fontFamily: _kFontFam);
  static const IconData facebook_circled = const IconData(0xf30d, fontFamily: _kFontFam);
}
